from tkinter import *
from aes import *
from PIL import ImageTk, Image
from tkinter import messagebox
root = Tk()
root.geometry("600x400")
root.title("ENCRYPTION PROGRAM") 
root.call('wm', 'iconphoto',Tk._w,ImageTk.PhotoImage(Image.open('POWER.ico')))
##
def hide_frame():
    e1.grid_forget()
    e2.grid_forget()
    myLabel3.grid_forget()
    myLabel4.grid_forget()
    myLabel2.grid_forget()
    myLabel1.grid_forget()
    myButton.grid_forget()
    button_quit.grid_forget()
    third_frame.grid_forget()
    sec_frame.grid_forget()
    first_frame.grid_forget()

def file_two():
    hide_frame()
    sec_frame.grid(sticky=N+S+W+E)
    myLabel1 = Label(sec_frame,text="TEXT DECRYPTION")
    myLabel2 = Label(sec_frame,text="ADVANCED ENCRYPTION STANDARD")
    myLabel1.grid(row=0,column=1)
    myLabel2.grid(row=1,column=1)
    myLabel3=Label(sec_frame,text="TEXT",font="bold")
    myLabel3.grid(row=5,column=0,pady=40,ipadx=30)
    e1 = Entry(sec_frame,width=50,borderwidth=6)
    e1.grid(row=5,column=1,pady=40)
    e1.insert(0,"Enter text here")
    myLabel4=Label(sec_frame,text="KEY",font="bold")
    myLabel4.grid(row=6,column=0,pady=40,ipadx=30)
    e2 = Entry(sec_frame,width=50,borderwidth=6)
    e2.grid(row=6,column=1,pady=40)
    e2.insert(0,"Enter text here")
    myButton=Button(sec_frame,text="decrypt",fg="red",bg="white",command=popup,activeforeground="white",activebackground="black",relief="raised",bd=5)
    myButton.grid(row=7,column=1)
    button_quit=Button(sec_frame,text="exit program",command=root.quit,fg="red",bg="white",activeforeground="white",activebackground="black",relief="raised",bd=5)
    button_quit.grid(row=8,column=1,pady=10)


def file_three():
    hide_frame()
    third_frame.grid(sticky=N+S+W+E)
    myLabel1 = Label(third_frame,text="VERSION 1.0",font="bold")
    myLabel2 = Label(third_frame,text="A SMALL ENCRYPTION PROJECT")
    myLabel3 = Label(third_frame,text="DONE BY-")
    myLabel4 = Label(third_frame,text="PIJUSH BHUYAN")
    myLabel5 = Label(third_frame,text="BHASKAR JYOTI BHATTACHARYA")
    myLabel6 = Label(third_frame,text="ARITRA KAUSHIK")
    myLabel7 = Label(third_frame,text="SOUVIK BARUAH")
    myLabel8 = Label(third_frame,text="OPEN SOURCE",font="italic 10 ")
    myLabel9 = Label(third_frame,text="SOME REQUIRED FILES ARE TAKEN FROM INTERNET",font="italic 10")
    myLabel1.grid(row=0,column=0,columnspan=2,sticky=E,pady=20)
    myLabel2.grid(row=1,column=0,sticky=W)
    myLabel3.grid(row=2,column=0,sticky=W)
    myLabel4.grid(row=3,column=0,sticky=W)
    myLabel5.grid(row=4,column=0,sticky=W)
    myLabel6.grid(row=5,column=0,sticky=W)
    myLabel7.grid(row=6,column=0,sticky=W)
    myLabel8.grid(row=7,column=0,sticky=W,pady=10)
    myLabel9.grid(row=8,column=0,sticky=W)
    #myLabel10.grid(row=9,column=0)


def file_one():
    hide_frame()
    first_frame.grid(sticky=N+S+W+E)
    myLabel1 = Label(first_frame,text="TEXT ENCRYPTION")
    myLabel2 = Label(first_frame,text="ADVANCED ENCRYPTION STANDARD")
    myLabel1.grid(row=0,column=1)
    myLabel2.grid(row=1,column=1)
    myLabel3=Label(first_frame,text="TEXT",font="bold")
    myLabel3.grid(row=5,column=0,pady=40,ipadx=30)
    e1 = Entry(first_frame,width=50,borderwidth=6)
    e1.grid(row=5,column=1,pady=40)
    e1.insert(0,"Enter text here")
    myLabel4=Label(first_frame,text="KEY",font="bold")
    myLabel4.grid(row=6,column=0,pady=40,ipadx=30)
    e2 = Entry(first_frame,width=50,borderwidth=6)
    e2.grid(row=6,column=1,pady=40)
    e2.insert(0,"Enter text here")
    myButton=Button(first_frame,text="encrypt",fg="red",bg="white",command=popup,activeforeground="white",activebackground="black",relief="raised",bd=5)
    myButton.grid(row=7,column=1)
    button_quit=Button(first_frame,text="exit program",command=root.quit,fg="red",bg="white",activeforeground="white",activebackground="black",relief="raised",bd=5)
    button_quit.grid(row=8,column=1,pady=10)


menubar = Menu(root)
#op1 = Menu(menubar,tearoff=0)
#op2 = Menu(menubar,tearoff=0)
#op3 = Menu(menubar,tearoff=0)
menubar.add_command(label="ENCRYPT",activebackground="black",activeforeground="white",command=file_one)
menubar.add_command(label="DECRYPT",activebackground="black",activeforeground="white",command=file_two)
menubar.add_command(label="ABOUT",activebackground="black",activeforeground="white",command=file_three)
root.config(menu=menubar)
##
myLabel1 = Label(root,text="TEXT ENCRYPTION")
myLabel2 = Label(root,text="ADVANCED ENCRYPTION STANDARD")
myLabel1.grid(row=0,column=1)
myLabel2.grid(row=1,column=1)
##
myLabel3=Label(root,text="TEXT",font="bold")
myLabel3.grid(row=5,column=0,pady=40,ipadx=30)
e1 = Entry(root,width=50,borderwidth=6)
e1.grid(row=5,column=1,pady=40)
e1.insert(0,"Enter text here")
myLabel4=Label(root,text="KEY",font="bold")
myLabel4.grid(row=6,column=0,pady=40,ipadx=30)
e2 = Entry(root,width=50,borderwidth=6)
e2.grid(row=6,column=1,pady=40)
e2.insert(0,"Enter text here")
##
def popup():
    text=e1.get()
    key=e2.get()
    e1.delete(0,END)
    if(text==""):
        messagebox.showerror("ERROR","you didn't enter")
    else:
        output=aesEncrypt(text,key)
        messagebox.showinfo("ENCRYPTED OUTPUT",output)
##
myButton=Button(root,text="encrpt",fg="red",bg="white",command=popup,activeforeground="white",activebackground="black",relief="raised",bd=5)
myButton.grid(row=7,column=1)
button_quit=Button(root,text="exit program",command=root.quit,fg="red",bg="white",activeforeground="white",activebackground="black",relief="raised",bd=5)
button_quit.grid(row=8,column=1,pady=10)
##
sec_frame = Frame(root,width=600,height=400)
third_frame = Frame(root,width=600,height=400)
first_frame = Frame(root,width=600,height=400)
root.mainloop()
